In [1]:
import numpy as np

In [2]:
def get_cc(grid):
    '''
    https://www.careercup.com/question?id=14948781
    '''
    
    # First, convert the 1/0 grid into an adjacency grid represented by a map
    graph = {}
    for row in range(0, len(grid)): 
        for column in range(0, len(grid[0])):
            key = (row, column)
            graph[key] = []
            if grid[row][column] == 1:
                graph[key].append(key)
            if column < len(grid[0]) - 1 and grid[row][column] == 1 and grid[row][column+1] == 1: 
                graph[key].append((row, column+1))
            if column >= 1 and grid[row][column] == 1 and grid[row][column-1] == 1: 
                graph[key].append((row, column-1))
            if row < len(grid) - 1 and grid[row][column] == 1 and grid[row+1][column] == 1: 
                graph[key].append((row+1, column))
            if row >= 1 and grid[row][column] == 1 and grid[row-1][column] == 1: 
                graph[key].append((row-1, column))

    # Counting the connected components 
    # Can also use BFS, too. 
    def dfs(visited, graph, node):
        if node not in visited:
            connected_components[counter].append(node)
            visited.add(node)
            for neighbour in graph[node]:
                dfs(visited, graph, neighbour)

    counter = 0
    visited = set()
    connected_components = []
    for node in graph.keys(): 
        if node not in visited and len(graph[node]) > 0:
            connected_components.append([])
            dfs(visited, graph, node)
            counter += 1

    return connected_components

In [3]:
# %%timeit

matrix = [
    [1, 1, 0, 1, 0, 1], 
    [0, 0, 1, 0, 0, 1], 
    [0, 1, 1, 1, 0, 1], 
    [0, 0, 1, 0, 0, 1], 
]

get_cc(np.array(matrix))

[[(0, 0), (0, 1)],
 [(0, 3)],
 [(0, 5), (1, 5), (2, 5), (3, 5)],
 [(1, 2), (2, 2), (2, 3), (2, 1), (3, 2)]]

In [4]:
%%timeit

get_cc(np.random.rand(100,100).round())

56.1 ms ± 4.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
0 - empty
1 - player 1
2 - player 2
7 - inactive border
8 - active border
9 - off grid

In [5]:
rows = 5
cols = 5 
grid = np.zeros([rows*2-1, cols*2-1], dtype=int)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
grid[1::2,:] = 7
grid[:,1::2] = 7
grid[1::2,1::2] = 9
grid

array([[0, 7, 0, 7, 0, 7, 0, 7, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 7, 0, 7, 0, 7, 0, 7, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 7, 0, 7, 0, 7, 0, 7, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 7, 0, 7, 0, 7, 0, 7, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 7, 0, 7, 0, 7, 0, 7, 0]])

In [7]:
def get_cc0(grid):
    '''
    https://www.careercup.com/question?id=14948781
    '''
    
    # First, convert the 1/0 grid into an adjacency grid represented by a map
    graph = {}
    for row in range(0, len(grid), 2): 
        for column in range(0, len(grid[0]), 2):
            key = (row, column)
            graph[key] = []
            # adding the home key
            if grid[row][column] == 0:
                graph[key].append(key)
            # (1) checking if within bounds (2) checking if empty (3) checking if no adjacent border (4) checking if adjacent square is empty
            if column < len(grid[0]) - 1 and grid[row][column] == 0 and grid[row][column+1] == 7 and grid[row][column+2] == 0: 
                graph[key].append((row, column+2))
            if column >= 1 and grid[row][column] == 0 and grid[row][column-1] == 7 and grid[row][column-2] == 0: 
                graph[key].append((row, column-2))
            if row < len(grid) - 1 and grid[row][column] == 0 and grid[row+1][column] == 7 and grid[row+2][column] == 0: 
                graph[key].append((row+2, column))
            if row >= 1 and grid[row][column] == 0 and grid[row-1][column] == 7 and grid[row-2][column] == 0: 
                graph[key].append((row-2, column))

    # Counting the connected components 
    # Can also use BFS, too. 
    def dfs(visited, graph, node):
        if node not in visited:
            connected_components[counter].append(node)
            visited.add(node)
            for neighbour in graph[node]:
                dfs(visited, graph, neighbour)

    counter = 0
    visited = set()
    connected_components = []
    for node in graph.keys(): 
        if node not in visited and len(graph[node]) > 0:
            connected_components.append([])
            dfs(visited, graph, node)
            counter += 1

    return connected_components

In [8]:
get_cc0(grid)

[[(0, 0),
  (0, 2),
  (0, 4),
  (0, 6),
  (0, 8),
  (2, 8),
  (2, 6),
  (2, 4),
  (2, 2),
  (2, 0),
  (4, 0),
  (4, 2),
  (4, 4),
  (4, 6),
  (4, 8),
  (6, 8),
  (6, 6),
  (6, 4),
  (6, 2),
  (6, 0),
  (8, 0),
  (8, 2),
  (8, 4),
  (8, 6),
  (8, 8)]]

In [9]:
grid[:,3] = 8
grid

array([[0, 7, 0, 8, 0, 7, 0, 7, 0],
       [7, 9, 7, 8, 7, 9, 7, 9, 7],
       [0, 7, 0, 8, 0, 7, 0, 7, 0],
       [7, 9, 7, 8, 7, 9, 7, 9, 7],
       [0, 7, 0, 8, 0, 7, 0, 7, 0],
       [7, 9, 7, 8, 7, 9, 7, 9, 7],
       [0, 7, 0, 8, 0, 7, 0, 7, 0],
       [7, 9, 7, 8, 7, 9, 7, 9, 7],
       [0, 7, 0, 8, 0, 7, 0, 7, 0]])

In [10]:
get_cc0(grid)

[[(0, 0),
  (0, 2),
  (2, 2),
  (2, 0),
  (4, 0),
  (4, 2),
  (6, 2),
  (6, 0),
  (8, 0),
  (8, 2)],
 [(0, 4),
  (0, 6),
  (0, 8),
  (2, 8),
  (2, 6),
  (2, 4),
  (4, 4),
  (4, 6),
  (4, 8),
  (6, 8),
  (6, 6),
  (6, 4),
  (8, 4),
  (8, 6),
  (8, 8)]]

In [11]:
rows = 6
cols = 6
grid = np.zeros([rows, cols], dtype=int)
row_borders = np.ones([rows-1, cols], dtype=int)*7
col_borders = np.ones([rows, cols-1], dtype=int)*8

In [12]:
row_borders

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [13]:
col_borders

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [14]:
out = np.zeros([grid.shape[0]*2-1, grid.shape[1]], dtype=int)
out[0::2,:] = grid
out[1::2,:] = row_borders


out2 = np.zeros([out.shape[0], out.shape[1]*2-1], dtype=int)
out2[:,0::2] = out
out2[0::2,1::2] = col_borders

out2[1::2,1::2] = 9

out2

array([[0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0]])

In [15]:
def merge(grid, rows, cols):
    # inserting rows
    out1 = np.zeros([grid.shape[0]*2-1, grid.shape[1]], dtype=int)
    out1[0::2,:] = grid
    out1[1::2,:] = rows

    # inserting columns
    out2 = np.zeros([out1.shape[0], out1.shape[1]*2-1], dtype=int)
    out2[:,0::2] = out1
    out2[0::2,1::2] = cols

    # overwritting corners
    out2[1::2,1::2] = 9
    return out2

In [16]:
grid_merged = merge(grid, row_borders, col_borders)
grid_merged

array([[0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0],
       [7, 9, 7, 9, 7, 9, 7, 9, 7, 9, 7],
       [0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0]])

In [17]:
get_cc0(grid_merged)

[[(0, 0), (2, 0), (4, 0), (6, 0), (8, 0), (10, 0)],
 [(0, 2), (2, 2), (4, 2), (6, 2), (8, 2), (10, 2)],
 [(0, 4), (2, 4), (4, 4), (6, 4), (8, 4), (10, 4)],
 [(0, 6), (2, 6), (4, 6), (6, 6), (8, 6), (10, 6)],
 [(0, 8), (2, 8), (4, 8), (6, 8), (8, 8), (10, 8)],
 [(0, 10), (2, 10), (4, 10), (6, 10), (8, 10), (10, 10)]]

In [18]:
grid_merged[0::2,1::2]

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [19]:
def split(grid):
    return grid_merged[0::2,0::2], grid_merged[1::2,0::2], grid_merged[0::2,1::2]

In [20]:
split(grid_merged)

(array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]),
 array([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]]),
 array([[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]]))